spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#   aws 배포후 아래 환경변수 자동 적용
    url: jdbc:mysql://localhost:3306/gnb_local
    username: root
    password: dnsgkdtlf11
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
#logging:
#  level:
#    org:
#      springframework: DEBUG